# pubspec.yaml (corretto)
name: dm_assistant
description: A comprehensive D&D campaign management tool for Dungeon Masters
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Offline Storage – torna alla 3.x stabile
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Navigation
  go_router: ^16.0.0   # 16.x richiede Flutter 3.33

  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # UI
  flex_color_scheme: ^8.2.0
  flutter_staggered_grid_view: ^0.7.0

  # Utilities
  uuid: ^4.5.1
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1   # ← allineato alla 3.x

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/map_markers/